DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;


CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  username TEXT NOT NULL,
  filename TEXT NOT NULL,
  body TEXT NOT NULL,
  hash TEXT UNIQUE NOT NULL
);